package com.dep.soms.dto.person;

import lombok.Data;
import java.time.LocalDate;

@Data
public class PersonRegistrationRequestDTO {
    private String firstName;
    private String middleName;
    private String lastName;
    private String email;
    private String phoneNumber;
    private String alternatePhone;
    private LocalDate dateOfBirth;
    private String gender;
    private String nationality;
    private String maritalStatus;
    private String streetAddress;
    private String city;
    private String stateProvince;
    private String postalCode;
    private String country;
    private String nationalId;
    private String passportNumber;
    private LocalDate passportExpiryDate;
    private String driversLicense;
    private LocalDate driversLicenseExpiry;
    private Integer heightCm;
    private Integer weightKg;
    private String primaryLanguage;
    private String otherLanguages;
    private String emergencyContactName;
    private String emergencyContactRelationship;
    private String emergencyPhone;
    private String emergencyContactAddress;
    private String nextOfKinName;
    private String nextOfKinRelationship;
    private String nextOfKinPhone;
    private String nextOfKinAddress;
    private String positionAppliedFor;
    private String departmentPreference;
    private String locationPreference;
    private LocalDate availabilityStartDate;
    private Double expectedSalary;
    private String workAuthorizationStatus;
    private String workPermitNumber;
    private LocalDate workPermitExpiry;
    private String highestEducationLevel;
    private String educationInstitution;
    private Integer graduationYear;
    private String professionalCertifications;
    private String skillsCompetencies;
    private Integer yearsOfExperience;
    private String previousEmployer1;
    private String previousPosition1;
    private String previousEmploymentDuration1;
    private String previousEmployer2;
    private String previousPosition2;
    private String previousEmploymentDuration2;
    private String previousEmployer3;
    private String previousPosition3;
    private String previousEmploymentDuration3;
    private String reference1Name;
    private String reference1Position;
    private String reference1Company;
    private String reference1Phone;
    private String reference1Email;
    private String reference2Name;
    private String reference2Position;
    private String reference2Company;
    private String reference2Phone;
    private String reference2Email;
    private String bloodType;
    private String medicalConditions;
    private String allergies;
    private String medications;
}